---
name: lcm
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - dags
  - jax>=0.3.0
  - jaxlib>=0.3.0
  - numpy
  - pandas

  # Testing dependencies
  - scipy
  - pybaum

  # Testing infrastructure
  - pytest
  - pytest-cov
  - pytest-xdist

  # Developer dependencies
  - estimagic
  - jupyterlab
  - matplotlib
  - numba
  - pdbpp
  - pre-commit
  - pydot

  # Documentation
  - sphinx
  - sphinx-panels
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme>=0.3.0

  # Install lcm locally
  - pip:
      - -e .
