name: lcm

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10
  - pip
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - estimagic
  - numpy
  - scipy
  - pandas
  - jax>=0.3.0
  - jaxlib>=0.3.0
  - networkx
  - dags
  - pybaum

  # Misc
  - numba
  - black
  - jupyterlab
  - matplotlib
  - nodejs
  - pdbpp
  - pre-commit
  - pydot
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda
  - sphinx
  - sphinx-panels
  - sphinxcontrib-bibtex
  - pydata-sphinx-theme>=0.3.0

  - pip:
      - -e .
