---
name: lcm-docs
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - setuptools_scm
  - sphinx
  - sphinxcontrib-bibtex
  - sphinx-copybutton
  - sphinx-design
  - sphinx-panels
  - myst-nb
  - furo
  - pip:
      - ../
