---
name: main
# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - '3.11'
          - '3.12'
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.7.0
        with:
          pixi-version: v0.22.0
          cache: true
      - name: Run pytest
        shell: bash -l {0}
        run: pixi run test
      - name: Upload coverage report
        if: runner.os == 'Linux' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
      - name: Run mypy
        if: runner.os == 'Linux' && matrix.python-version == '3.12'
        shell: bash -l {0}
        run: pixi run mypy
