---
name: main
# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - '3.12'
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.41.4
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: test-cpu
          activate-environment: true
          frozen: true
      - name: Run pytest
        shell: bash {0}
        run: pixi run -e test-cpu tests
        if: runner.os != 'Linux' || matrix.python-version != '3.12'
      - name: Run pytest and collect coverage
        shell: bash {0}
        run: pixi run -e test-cpu tests-with-cov
        if: runner.os == 'Linux' && matrix.python-version == '3.12'
      - name: Upload coverage report
        if: runner.os == 'Linux' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v4
  run-mypy:
    name: Run mypy on Python 3.12
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.41.4
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: test-cpu
          frozen: true
      - name: Run mypy
        shell: bash {0}
        run: pixi run -e test-cpu mypy
  # run-explanation-notebooks:
  #   name: Run explanation notebooks on Python 3.12
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: prefix-dev/setup-pixi@v0.8.1
  #       with:
  #         pixi-version: v0.41.4
  #         cache: true
  #         cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
  #         environments: test-cpu
  #         frozen: true
  #     - name: Run explanation notebooks
  #       shell: bash {0}
  #       run: pixi run -e test-cpu explanation-notebooks
